#!/usr/bin/perl -w

# (C) 2007 Dr. Thomas Fischbacher
#
# Compare two matrices dumped to files.
# This little helper is used to validate the matrices
# generated by new ML code (and debug-dumped with Mpi_petsc.matrix_debugdump_to_file)
# against matrices generated by properly working older code.

my($mx1,$mx2)=@ARGV;

my $data_mx1=get_matrix_entries($mx1);
my $data_mx2=get_matrix_entries($mx2);

my $nr_mx1_entries=$#$data_mx1+1-2;
my $nr_mx2_entries=$#$data_mx2+1-2;

$nr_mx1_entries == $nr_mx2_entries or die "Incompatible matrices!\n";

my $dist=0;

for(my $i=0;$i<$nr_mx1_entries;$i++)
  {
    my $x=$data_mx1->[$i+2]-$data_mx2->[$i+2];
    $dist+=$x*$x;
  }

printf "MX1: %4d x %4d, MX2: %4d x %4d - Delta: %f\n",
  $data_mx1->[0],$data_mx1->[1],$data_mx2->[0],$data_mx2->[1],sqrt($dist);


sub get_matrix_entries
  {
    my($filename)=@_;

    my $size=-s $filename;
    my $buf="\x00"x$size;
    open F, $filename and do
      {
	$size==read F, $buf, $size or die "Fatal: reading '$filename' failed: $!\n";
	close F;
      };
    my $nr_vals=$size/8;
    my $vals=[unpack "d*", $buf];
    
    return $vals;
  }

